version: "3.7"

volumes:
  db_data:

services:
  carry-image:
    image: 'carry'
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
      args:
        INSTALL_DEV: true

  bot:
    image: 'carry'
    volumes:
      - ./carry:/app/carry
      - ./settings.toml:/app/settings.toml
      - ./.secrets.toml:/app/.secrets.toml
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
    command: watchmedo auto-restart --recursive --pattern="*.py;settings.toml" --directory="/app/" python -- -m carry.telegram_bot
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - db_data:/data/db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=carry
